import { Question } from 'common/models';

export const PERSONA_QUESTIONS: Question[] = [
	{ id: '1', questionText: '내 이름' },
	{ id: '2', questionText: '생일' },
	{ id: '3', questionText: '키' },
	{ id: '4', questionText: '최근 관심사' },
	{ id: '5', questionText: '집에서 심심할 때 하는 일' },
	{ id: '6', questionText: '아침에 일어나서 먼저 하는 일' },
	{ id: '7', questionText: '좋아하는 가수' },
	{ id: '8', questionText: '좋아하는 배우' },
	{ id: '9', questionText: '요즘 자주 듣는 노래' },
	{ id: '10', questionText: '인생 노래' },
	{ id: '11', questionText: '인생 영화' },
	{ id: '12', questionText: '인생 책' },
	{ id: '13', questionText: '좋아하는 음식' },
	{ id: '14', questionText: '싫어하는 음식' },
	{ id: '15', questionText: '이상형' },
	{ id: '16', questionText: '친구랑 친해지는 법' },
	{ id: '17', questionText: '요즘 하고 싶은 것' },
	{ id: '18', questionText: '연하 vs 동갑 vs 연하' },
	{ id: '19', questionText: '목표 (꿈, 장래희망)' },
	{ id: '20', questionText: '자기 전에 마지막으로 하는 일' },
	{ id: '21', questionText: 'MBTI' },
	{ id: '22', questionText: '습관, 버릇' },
	{ id: '23', questionText: '취미' },
	{ id: '24', questionText: '특기' },
	{ id: '25', questionText: '좋아하는 계절' },
	{ id: '26', questionText: '낮, 밤중 내가 활발한 시간' },
	{ id: '27', questionText: '즐겨보는 유튜버' },
	{ id: '28', questionText: '좋아하는 색깔' },
	{ id: '29', questionText: '좋아하는 과일' },
	{ id: '30', questionText: '좋아하는 반찬' },
	{ id: '31', questionText: '지금 카톡 프사' },
	{ id: '32', questionText: '내 성격을 한마디로 표현하면?' },
	{ id: '33', questionText: '오래 연애한 기간' },
	{ id: '34', questionText: '짧게 연애한 기간' },
	{ id: '35', questionText: '잠이 안 올 때 하는 것' },
	{ id: '36', questionText: '좋아하는 라면' },
	{ id: '37', questionText: '답장 평균 시간' },
	{ id: '38', questionText: '아침식사 유무' },
	{ id: '39', questionText: '낯가림 유무' },
	{ id: '40', questionText: '단 음식 호, 불호' },
	{ id: '41', questionText: '매운 음식 호, 불호' },
	{ id: '42', questionText: '노래방 가면 항상 부르는 애창곡' },
	{ id: '43', questionText: '세상에서 무서운 것' },
	{ id: '44', questionText: '민트 초코 호, 불호' },
	{ id: '45', questionText: '좋아하는 베라 맛' },
	{ id: '46', questionText: '전화 VS 카톡' },
	{ id: '47', questionText: '스트레스 해소법' },
	{ id: '48', questionText: '인생 좌우명' },
	{ id: '49', questionText: '많이 사용하는 앱' },
	{ id: '50', questionText: '가계부 호, 불호' },
	{ id: '51', questionText: '내가 가진 것 중 비싼 것' },
	{ id: '52', questionText: '소중한 물건' },
	{ id: '53', questionText: '진짜 예쁜 것' },
	{ id: '54', questionText: '진짜 쓸모없는 것' },
	{ id: '55', questionText: '진짜 아끼는 물건' },
	{ id: '56', questionText: '좋아하는 숫자' },
	{ id: '57', questionText: '좋아하는 옷 브랜드' },
	{ id: '58', questionText: '내 추억이 담긴 물건' },
	{ id: '59', questionText: '내가 하는 SNS' },
	{ id: '60', questionText: '내 게임 닉네임' },
	{ id: '61', questionText: '내 게임 닉네임 뜻' },
	{ id: '62', questionText: '돈 생기면 많이 쓰는 곳' },
	{ id: '63', questionText: '자주 하는 악세사리' },
	{ id: '64', questionText: '짜장 VS 짬뽕' },
	{ id: '65', questionText: '찍먹 VS 부먹' },
	{ id: '66', questionText: '물냉 VS 비냉' },
	{ id: '67', questionText: '내가 잘하는 음식' },
	{ id: '68', questionText: '좋아하는 동물' },
	{ id: '69', questionText: '나의 별명' },
	{ id: '70', questionText: '싫어하는 색' },
	{ id: '71', questionText: '가족관계' },
	{ id: '72', questionText: '나의 혈액형' },
	{ id: '73', questionText: '내 발 사이즈' },
	{ id: '74', questionText: '요즘 갖고 싶은 물건' },
	{ id: '75', questionText: '내가 결혼하고 싶은 나이' },
	{ id: '76', questionText: '내가 좋아하는 꽃' },
	{ id: '77', questionText: '요즘 심각한 고민은?' },
	{ id: '78', questionText: '내가 많이 아팠을 때' },
	{ id: '79', questionText: '친구가 약속시간 1시간 늦었을 때 나는?' },
	{ id: '80', questionText: '1년 전 나에게 해주고 싶은 말' },
	{ id: '81', questionText: '내가 가진 추억 중 가장 어릴 때의 기억' },
	{ id: '82', questionText: '내가 가진 기억 중 무서웠던 기억' },
	{ id: '83', questionText: '백만 원이 생기면 하고 싶은 것' },
	{ id: '84', questionText: '하루 식사 횟수' },
	{ id: '85', questionText: '좋아하는 와인?' },
	{ id: '86', questionText: '남들에 비해 못하는 것?' },
	{ id: '87', questionText: '주량' },
	{ id: '88', questionText: '나의 TMI' },
	{ id: '89', questionText: '내가 가진 기억 중 신기한 기억' },
	{ id: '90', questionText: '몇 살까지 살고 싶은지' },
	{ id: '91', questionText: '나의 종교' },
	{ id: '92', questionText: '좋아하는 단어' },
	{ id: '93', questionText: '내가 자주 쓰는 말' },
	{ id: '94', questionText: '내가 좋아하는 공간' },
	{ id: '95', questionText: '여행 가면 가고 싶은 지역, 나라' },
	{ id: '96', questionText: '여행에 꼭 가져가야 할 나만의 필수 템' },
	{ id: '97', questionText: '내가 갖고 싶은 초능력' },
	{ id: '98', questionText: '죽어서 영혼이 되면 먼저 하고 싶은 일' },
	{ id: '99', questionText: '백문 백답 이후 할 일' },
	{ id: '100', questionText: '문답을 마치고 느낀 점' },
	{ id: '101', questionText: '자주 가는 여행지는 어디인가요?' },
	{ id: '102', questionText: '가고 싶은 공연이나 전시회가 현재 있나요?' },
	{ id: '103', questionText: '내가 참여하고 있는 동호회는?' },
	{ id: '104', questionText: '내 경험 중 가장 뿌듯했던 순간은 언제인가요?' },
	{
		id: '105',
		questionText:
			'중요한 사람과 함께하는 데 이용할 수 있는 취미 활동이 어떤 것이 있나요?',
	},
];

export const TONE_QUESTIONS: Question[] = [
	{ id: '1', questionText: '오늘 하루를 어떻게 보냈는지 말해줄 수 있을까요?' },
	{
		id: '2',
		questionText: '좋아하는 영화나 드라마는 무엇인가요? 그 이유는 무엇인가요?',
	},
	{
		id: '3',
		questionText: '감동받았던 일이나 경험은 무엇인가요?',
	},
];
